-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:9ceae707798c695750d20592d44faaab$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "0.png",
				spriteColorRect = { x = 0, y = 0, width = 90, height = 94 },
				textureRect = { x = 2, y = 2, width = 90, height = 94 },
				spriteSourceSize = { width = 90, height = 94 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "1.png",
				spriteColorRect = { x = 0, y = 0, width = 92, height = 94 },
				textureRect = { x = 94, y = 2, width = 92, height = 94 },
				spriteSourceSize = { width = 92, height = 94 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "2.png",
				spriteColorRect = { x = 0, y = 0, width = 90, height = 94 },
				textureRect = { x = 2, y = 98, width = 90, height = 94 },
				spriteSourceSize = { width = 90, height = 94 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "3.png",
				spriteColorRect = { x = 0, y = 0, width = 76, height = 124 },
				textureRect = { x = 94, y = 98, width = 76, height = 124 },
				spriteSourceSize = { width = 76, height = 124 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "4.png",
				spriteColorRect = { x = 0, y = 0, width = 120, height = 94 },
				textureRect = { x = 2, y = 224, width = 120, height = 94 },
				spriteSourceSize = { width = 120, height = 94 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "5.png",
				spriteColorRect = { x = 0, y = 0, width = 120, height = 94 },
				textureRect = { x = 124, y = 224, width = 120, height = 94 },
				spriteSourceSize = { width = 120, height = 94 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "6.png",
				spriteColorRect = { x = 0, y = 0, width = 90, height = 96 },
				textureRect = { x = 2, y = 320, width = 90, height = 96 },
				spriteSourceSize = { width = 90, height = 96 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "7.png",
				spriteColorRect = { x = 0, y = 0, width = 88, height = 88 },
				textureRect = { x = 94, y = 320, width = 88, height = 88 },
				spriteSourceSize = { width = 88, height = 88 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "8.png",
				spriteColorRect = { x = 0, y = 0, width = 146, height = 24 },
				textureRect = { x = 2, y = 418, width = 146, height = 24 },
				spriteSourceSize = { width = 146, height = 24 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

