-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:d840bc15d2c69dfe252cf575ce62fd61$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "0.png",
				spriteColorRect = { x = 0, y = 0, width = 110, height = 78 },
				textureRect = { x = 2, y = 2, width = 110, height = 78 },
				spriteSourceSize = { width = 110, height = 78 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "1.png",
				spriteColorRect = { x = 0, y = 0, width = 108, height = 76 },
				textureRect = { x = 114, y = 2, width = 108, height = 76 },
				spriteSourceSize = { width = 108, height = 76 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "2.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 111 },
				textureRect = { x = 2, y = 82, width = 100, height = 111 },
				spriteSourceSize = { width = 100, height = 111 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "3.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 77 },
				textureRect = { x = 104, y = 82, width = 130, height = 77 },
				spriteSourceSize = { width = 130, height = 77 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "4.png",
				spriteColorRect = { x = 0, y = 0, width = 77, height = 71 },
				textureRect = { x = 2, y = 195, width = 77, height = 71 },
				spriteSourceSize = { width = 77, height = 71 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "5.png",
				spriteColorRect = { x = 0, y = 0, width = 125, height = 34 },
				textureRect = { x = 81, y = 195, width = 125, height = 34 },
				spriteSourceSize = { width = 125, height = 34 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

