-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:1362b284beb43887bb3502b8c3934540$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "0.png",
				spriteColorRect = { x = 1, y = 0, width = 60, height = 148 },
				textureRect = { x = 131, y = 230, width = 60, height = 148 },
				spriteSourceSize = { width = 66, height = 150 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "1.png",
				spriteColorRect = { x = 1, y = 0, width = 62, height = 151 },
				textureRect = { x = 67, y = 320, width = 62, height = 151 },
				spriteSourceSize = { width = 68, height = 153 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "2.png",
				spriteColorRect = { x = 1, y = 0, width = 63, height = 153 },
				textureRect = { x = 2, y = 320, width = 63, height = 153 },
				spriteSourceSize = { width = 69, height = 153 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "3.png",
				spriteColorRect = { x = 0, y = 0, width = 120, height = 110 },
				textureRect = { x = 2, y = 208, width = 120, height = 110 },
				spriteSourceSize = { width = 122, height = 110 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "4.png",
				spriteColorRect = { x = 0, y = 0, width = 140, height = 101 },
				textureRect = { x = 2, y = 2, width = 140, height = 101 },
				spriteSourceSize = { width = 140, height = 101 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "5.png",
				spriteColorRect = { x = 0, y = 0, width = 137, height = 101 },
				textureRect = { x = 2, y = 105, width = 137, height = 101 },
				spriteSourceSize = { width = 137, height = 101 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "6.png",
				spriteColorRect = { x = 1, y = 0, width = 72, height = 135 },
				textureRect = { x = 144, y = 93, width = 72, height = 135 },
				spriteSourceSize = { width = 74, height = 135 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "7.png",
				spriteColorRect = { x = 0, y = 0, width = 90, height = 89 },
				textureRect = { x = 144, y = 2, width = 90, height = 89 },
				spriteSourceSize = { width = 92, height = 99 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "8.png",
				spriteColorRect = { x = 0, y = 0, width = 56, height = 36 },
				textureRect = { x = 67, y = 473, width = 56, height = 36 },
				spriteSourceSize = { width = 56, height = 38 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

