-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:9b472db1c1f7e72fd6cc9162b4d1dec9$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "0.png",
				spriteColorRect = { x = 0, y = 0, width = 132, height = 65 },
				textureRect = { x = 2, y = 134, width = 132, height = 65 },
				spriteSourceSize = { width = 132, height = 65 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "1.png",
				spriteColorRect = { x = 1, y = 0, width = 131, height = 63 },
				textureRect = { x = 2, y = 201, width = 131, height = 63 },
				spriteSourceSize = { width = 133, height = 63 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "2.png",
				spriteColorRect = { x = 0, y = 0, width = 134, height = 65 },
				textureRect = { x = 2, y = 67, width = 134, height = 65 },
				spriteSourceSize = { width = 134, height = 65 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "3.png",
				spriteColorRect = { x = 0, y = 0, width = 135, height = 63 },
				textureRect = { x = 2, y = 2, width = 135, height = 63 },
				spriteSourceSize = { width = 135, height = 63 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

