-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:55b9d40b0436583addd7be417c1d7fb9$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "0.png",
				spriteColorRect = { x = 0, y = 0, width = 120, height = 59 },
				textureRect = { x = 2, y = 122, width = 120, height = 59 },
				spriteSourceSize = { width = 120, height = 59 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "1.png",
				spriteColorRect = { x = 1, y = 0, width = 119, height = 57 },
				textureRect = { x = 2, y = 183, width = 119, height = 57 },
				spriteSourceSize = { width = 121, height = 57 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "2.png",
				spriteColorRect = { x = 0, y = 0, width = 122, height = 59 },
				textureRect = { x = 2, y = 61, width = 122, height = 59 },
				spriteSourceSize = { width = 122, height = 59 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "3.png",
				spriteColorRect = { x = 0, y = 0, width = 123, height = 57 },
				textureRect = { x = 2, y = 2, width = 123, height = 57 },
				spriteSourceSize = { width = 123, height = 57 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

