-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:137631fffa32e3f4de68a20eb6a736b1$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "0.png",
				spriteColorRect = { x = 0, y = 0, width = 114, height = 101 },
				textureRect = { x = 2, y = 2, width = 114, height = 101 },
				spriteSourceSize = { width = 114, height = 101 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "1.png",
				spriteColorRect = { x = 0, y = 0, width = 113, height = 102 },
				textureRect = { x = 118, y = 2, width = 113, height = 102 },
				spriteSourceSize = { width = 113, height = 102 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "10.png",
				spriteColorRect = { x = 0, y = 0, width = 75, height = 104 },
				textureRect = { x = 2, y = 106, width = 75, height = 104 },
				spriteSourceSize = { width = 75, height = 104 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "2.png",
				spriteColorRect = { x = 0, y = 0, width = 104, height = 102 },
				textureRect = { x = 79, y = 106, width = 104, height = 102 },
				spriteSourceSize = { width = 104, height = 102 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "3.png",
				spriteColorRect = { x = 0, y = 0, width = 59, height = 104 },
				textureRect = { x = 185, y = 106, width = 59, height = 104 },
				spriteSourceSize = { width = 59, height = 104 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "4.png",
				spriteColorRect = { x = 0, y = 0, width = 47, height = 56 },
				textureRect = { x = 2, y = 212, width = 47, height = 56 },
				spriteSourceSize = { width = 47, height = 56 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "5.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 110 },
				textureRect = { x = 51, y = 212, width = 60, height = 110 },
				spriteSourceSize = { width = 60, height = 110 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "6.png",
				spriteColorRect = { x = 0, y = 0, width = 51, height = 108 },
				textureRect = { x = 113, y = 212, width = 51, height = 108 },
				spriteSourceSize = { width = 51, height = 108 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "7.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 107 },
				textureRect = { x = 166, y = 212, width = 62, height = 107 },
				spriteSourceSize = { width = 62, height = 107 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "8.png",
				spriteColorRect = { x = 0, y = 0, width = 75, height = 102 },
				textureRect = { x = 2, y = 324, width = 75, height = 102 },
				spriteSourceSize = { width = 75, height = 102 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "9.png",
				spriteColorRect = { x = 0, y = 0, width = 78, height = 102 },
				textureRect = { x = 79, y = 324, width = 78, height = 102 },
				spriteSourceSize = { width = 78, height = 102 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

