-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:aa426e1f86c3630f0327f2492d7d39a6$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "0.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 101 },
				textureRect = { x = 189, y = 217, width = 54, height = 101 },
				spriteSourceSize = { width = 54, height = 101 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "1.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 101 },
				textureRect = { x = 133, y = 217, width = 54, height = 101 },
				spriteSourceSize = { width = 54, height = 101 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "2.png",
				spriteColorRect = { x = 0, y = 0, width = 53, height = 102 },
				textureRect = { x = 2, y = 313, width = 53, height = 102 },
				spriteSourceSize = { width = 53, height = 102 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "3.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 102 },
				textureRect = { x = 57, y = 371, width = 48, height = 102 },
				spriteSourceSize = { width = 48, height = 102 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "4.png",
				spriteColorRect = { x = 0, y = 0, width = 46, height = 102 },
				textureRect = { x = 107, y = 371, width = 46, height = 102 },
				spriteSourceSize = { width = 46, height = 102 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "5.png",
				spriteColorRect = { x = 0, y = 0, width = 53, height = 109 },
				textureRect = { x = 60, y = 260, width = 53, height = 109 },
				spriteSourceSize = { width = 53, height = 109 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "6.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 102 },
				textureRect = { x = 2, y = 105, width = 66, height = 102 },
				spriteSourceSize = { width = 66, height = 102 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "7.png",
				spriteColorRect = { x = 0, y = 0, width = 75, height = 110 },
				textureRect = { x = 94, y = 2, width = 75, height = 110 },
				spriteSourceSize = { width = 75, height = 110 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "8.png",
				spriteColorRect = { x = 0, y = 0, width = 70, height = 109 },
				textureRect = { x = 171, y = 106, width = 70, height = 109 },
				spriteSourceSize = { width = 70, height = 109 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "9.png",
				spriteColorRect = { x = 0, y = 0, width = 61, height = 110 },
				textureRect = { x = 70, y = 148, width = 61, height = 110 },
				spriteSourceSize = { width = 61, height = 110 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "91.png",
				spriteColorRect = { x = 0, y = 0, width = 56, height = 102 },
				textureRect = { x = 2, y = 209, width = 56, height = 102 },
				spriteSourceSize = { width = 56, height = 102 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "92.png",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 102 },
				textureRect = { x = 155, y = 320, width = 43, height = 102 },
				spriteSourceSize = { width = 43, height = 102 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "93.png",
				spriteColorRect = { x = 0, y = 0, width = 75, height = 102 },
				textureRect = { x = 171, y = 2, width = 75, height = 102 },
				spriteSourceSize = { width = 75, height = 102 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "94.png",
				spriteColorRect = { x = 0, y = 0, width = 90, height = 101 },
				textureRect = { x = 2, y = 2, width = 90, height = 101 },
				spriteSourceSize = { width = 90, height = 101 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "95.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 91 },
				textureRect = { x = 2, y = 417, width = 48, height = 91 },
				spriteSourceSize = { width = 48, height = 91 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "96.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 32 },
				textureRect = { x = 70, y = 114, width = 62, height = 32 },
				spriteSourceSize = { width = 62, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

