-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:c5656135027bb2c5e903e31c6b366c5d$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "0.png",
				spriteColorRect = { x = 0, y = 0, width = 49, height = 99 },
				textureRect = { x = 2, y = 364, width = 49, height = 99 },
				spriteSourceSize = { width = 49, height = 99 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "1.png",
				spriteColorRect = { x = 0, y = 0, width = 53, height = 101 },
				textureRect = { x = 2, y = 261, width = 53, height = 101 },
				spriteSourceSize = { width = 53, height = 101 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "2.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 99 },
				textureRect = { x = 149, y = 103, width = 60, height = 99 },
				spriteSourceSize = { width = 60, height = 99 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "3.png",
				spriteColorRect = { x = 0, y = 0, width = 69, height = 99 },
				textureRect = { x = 78, y = 103, width = 69, height = 99 },
				spriteSourceSize = { width = 69, height = 99 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "4.png",
				spriteColorRect = { x = 0, y = 0, width = 95, height = 99 },
				textureRect = { x = 112, y = 2, width = 95, height = 99 },
				spriteSourceSize = { width = 95, height = 99 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "5.png",
				spriteColorRect = { x = 0, y = 0, width = 63, height = 133 },
				textureRect = { x = 2, y = 126, width = 63, height = 133 },
				spriteSourceSize = { width = 63, height = 133 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "6.png",
				spriteColorRect = { x = 0, y = 0, width = 108, height = 94 },
				textureRect = { x = 2, y = 2, width = 108, height = 94 },
				spriteSourceSize = { width = 108, height = 94 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "7.png",
				spriteColorRect = { x = 0, y = 0, width = 49, height = 99 },
				textureRect = { x = 2, y = 364, width = 49, height = 99 },
				spriteSourceSize = { width = 49, height = 99 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "8.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 97 },
				textureRect = { x = 67, y = 204, width = 60, height = 97 },
				spriteSourceSize = { width = 60, height = 97 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "91.png",
				spriteColorRect = { x = 0, y = 1, width = 74, height = 26 },
				textureRect = { x = 2, y = 98, width = 74, height = 26 },
				spriteSourceSize = { width = 74, height = 28 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

